{
 "title": "Performance-Dashboard-v2",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "CPU and Memory Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "rawSql": "select to_timestamp(timestamp_usecs / 1000000) as time,memory_usage_percent as memory from reporting.resource_usage_stats where entity_type = 1 order by time"
      }
     ]
    },
    {
     "title": "Cluster Utilization",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "select 100 * physical_usage_bytes / cluster_capacity_bytes as percent_full from reporting.cluster"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "rawSql": "select to_timestamp(timestamp_usecs / 1000000) as time, cpu_usage_percent as CPU from reporting.resource_usage_stats where entity_type = 1 order by time;"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "select to_timestamp(timestamp_usecs / 1000000) as time,memory_usage_percent as memory from reporting.resource_usage_stats where entity_type = 1 order by time"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "select to_timestamp(timestamp_usecs / 1000000) as time, cpu_usage_percent as CPU from reporting.resource_usage_stats where entity_type = 1 order by time;"
      }
     ]
    }
   ]
  },
  {
   "title": "IO Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Latest Read Throughput (MiB)",
     "type": "stat",
     "description": "Read throughput on the cluster (in MiB)",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "select to_timestamp(timestamp_usecs / 1000000) as time, read_throughput_bytes_per_sec/1048576 as read_throughput_mib from reporting.io_performance_stats where entity_type = 1;"
      }
     ]
    },
    {
     "title": "Latest Write Throughput (MiB)",
     "type": "stat",
     "description": "Write throughput on the cluster (in MiB)",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "select to_timestamp(timestamp_usecs / 1000000) as time, write_throughput_bytes_per_sec/1048576 as write_throughput_mib from reporting.io_performance_stats where entity_type = 1;"
      }
     ]
    },
    {
     "title": "Latest Read IOPS",
     "type": "gauge",
     "description": "This graph shows the read IOPS over the entire cluster.",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "select to_timestamp(timestamp_usecs / 1000000) as time, read_iops from reporting.io_performance_stats where entity_type = 1 and read_iops <> 0 order by time;"
      }
     ]
    },
    {
     "title": "Latest Write IOPS",
     "type": "gauge",
     "description": "This graph shows the write IOPS over the entire cluster.",
     "gridPos": { "h": 3, "w": 4, "x": 12, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "select to_timestamp(timestamp_usecs / 1000000) as time, write_iops from reporting.io_performance_stats where entity_type = 1 and write_iops <> 0 order by time;"
      }
     ]
    },
    {
     "title": "Latest Read Latency (ms)",
     "type": "stat",
     "description": "Non-zero values for Write Latency on the cluster (in milliseconds)",
     "gridPos": { "h": 3, "w": 4, "x": 16, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "select to_timestamp(timestamp_usecs / 1000000) as time, read_latency_msecs from reporting.io_performance_stats where entity_type = 1 and read_latency_msecs <> 0 ORDER BY time"
      }
     ]
    },
    {
     "title": "Latest Write Latency (ms)",
     "type": "stat",
     "description": "Non-zero values for Write Latency on the cluster (in milliseconds)",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "select to_timestamp(timestamp_usecs / 1000000) as time, write_latency_msecs from reporting.io_performance_stats where entity_type = 1  and write_latency_msecs <> 0 ORDER BY time"
      }
     ]
    },
    {
     "title": "Read Throughput",
     "type": "timeseries",
     "description": "Read throughput on the cluster (in MiB)",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 5 },
     "targets": [
      {
       "rawSql": "select to_timestamp(timestamp_usecs / 1000000) as time, read_throughput_bytes_per_sec/1048576 as read_throughput_mib from reporting.io_performance_stats where entity_type = 1;"
      }
     ]
    },
    {
     "title": "Read IOPS",
     "type": "timeseries",
     "description": "This graph shows the read IOPS over the entire cluster.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 5 },
     "targets": [
      {
       "rawSql": "select to_timestamp(timestamp_usecs / 1000000) as time, read_iops from reporting.io_performance_stats where entity_type = 1 order by time;"
      }
     ]
    },
    {
     "title": "Read Latency",
     "type": "timeseries",
     "description": "Non-zero values for Read Latency on the cluster (in milliseconds)",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 5 },
     "targets": [
      {
       "rawSql": "select to_timestamp(timestamp_usecs / 1000000) as time, read_latency_msecs from reporting.io_performance_stats where entity_type = 1 ORDER BY time"
      }
     ]
    },
    {
     "title": "Write Throughput",
     "type": "timeseries",
     "description": "Write throughput on the cluster (in MiB)",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 13 },
     "targets": [
      {
       "rawSql": "select to_timestamp(timestamp_usecs / 1000000) as time, write_throughput_bytes_per_sec/1048576 as write_throughput_mib from reporting.io_performance_stats where entity_type = 1;"
      }
     ]
    },
    {
     "title": "Write IOPS",
     "type": "timeseries",
     "description": "This graph shows the write IOPS over the entire cluster.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 13 },
     "targets": [
      {
       "rawSql": "select to_timestamp(timestamp_usecs / 1000000) as time, write_iops from reporting.io_performance_stats where entity_type = 1 order by time;"
      }
     ]
    },
    {
     "title": "Write Latency",
     "type": "timeseries",
     "description": "Non-zero values for Write Latency on the cluster (in milliseconds)",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 13 },
     "targets": [
      {
       "rawSql": "select to_timestamp(timestamp_usecs / 1000000) as time, write_latency_msecs from reporting.io_performance_stats where entity_type = 1 ORDER BY time"
      }
     ]
    }
   ]
  },
  { "title": "View Dashboard", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "View List",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "rawSql": "select view_id, view_name , (logical_usage_bytes/1073741824) as logical_usage_GiB from reporting.views ORDER by logical_usage_bytes DESC;"
    }
   ]
  },
  {
   "title": "View Quota Consumption",
   "type": "bargauge",
   "description": "For views assigned a quota, this dashboard lists the usage of each view.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "\n\nselect view_name, 100 * logical_usage_bytes / logical_quota_bytes as quota_percent from reporting.views where logical_quota_bytes <> 0;"
    }
   ]
  }
 ]
}